### ISSUE TITLE
Null PTR

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/ChestDrop#2]
```
07.08 11:40:05 [Server] INFO SexyBacca99 issued server command: /nbt 
07.08 11:40:05 [Server] ERROR null 
07.08 11:40:05 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'nbt' in plugin ChestDrop v0.1.5 
07.08 11:40:05 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91] 
07.08 11:40:05 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91] 
07.08 11:40:05 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91] 
07.08 11:40:05 [Server] INFO Caused by: java.lang.NullPointerException 
07.08 11:40:05 [Server] INFO at org.primesoft.chestDrop.commands.DumpItemCommand.onCommand(DumpItemCommand.java:84) ~[?:?] 
07.08 11:40:05 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[custom10.jar:git-Spigot-a9631d2-67b2424] 
07.08 11:40:05 [Server] INFO ... 15 more
```

**Comment by SBPrime** [comment]
This error was caused by using not supported version of SPIGOT.
